[window]

opacity = 1.0

padding.x = 10
padding.y = 10

decorations = "Full"

[font]

normal.family = "JetBrainsMonoNL Nerd Font Mono"
bold.family = "JetBrainsMonoNL Nerd Font Mono"
italic.family = "JetBrainsMonoNL NerdFont Mono"
bold_italic.family = "JetBrainsMonoNL NerdFont Mono"

size = 15.0

